apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: task2
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: REPLACE_WITH_IMAGE # ← подставьте образ из задания
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "30Mi"
              cpu: "50m"
            limits:
              memory: "30Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
