apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: task2
  labels:
    app: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
